name: Publish package

on:
  push:
    branches: [ master, publish_test ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
#      - name: Test
#        run: dotnet test --no-build --verbosity normal 
#        env:
#          YandexProxy: ${{secrets.YANDEXPROXYURL}}
  publish:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish NuGet
        uses: Rebel028/publish-nuget@v2.6.0
        with:
          PROJECT_FILE_PATH: YandexMusicResolver/YandexMusicResolver.csproj
          NUGET_KEY: ${{secrets.NUGETAPIKEY}}
          NUGET_SOURCE: https://api.nuget.org/v3
          THOW_ERROR_IF_VERSION_EXISTS: false
      - name: Publish Github Packages
        uses: Rebel028/publish-nuget@v2.6.0
        with:
          PROJECT_FILE_PATH: YandexMusicResolver/YandexMusicResolver.csproj
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
          NUGET_SOURCE: https://nuget.pkg.github.com/SKProCH
          THOW_ERROR_IF_VERSION_EXISTS: false