name: Publish package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload aftifacts
      uses: actions/upload-artifact@v2
      with:
        name: project
        path: /
  run_tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download project artifacts
        uses: actions/download-artifact@v2
        with:
          name: project
          path: /
      - name: Test
        run: dotnet test --no-build --verbosity normal 
        env:
          YandexProxy: ${{secrets.YANDEXPROXYURL}}
  publish:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download project artifacts
        uses: actions/download-artifact@v2
        with:
          name: project
          path: /
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: YandexMusicResolver/YandexMusicResolver.csproj
          NUGET_KEY: ${{secrets.NUGETAPIKEY}}
